name: Build

on:
  workflow_dispatch:
    inputs:
      build_linux:
        description: 'Build Linux x64'
        type: boolean
        default: true
      build_android:
        description: 'Build Android'
        type: boolean
        default: true
      build_windows:
        description: 'Build Windows x64'
        type: boolean
        default: true
      build_mode:
        description: 'Build mode'
        type: choice
        options:
          - fast
          - full
        default: fast
      release_mode:
        description: 'Create GitHub Release'
        type: boolean
        default: false
      release_tag:
        description: 'Release tag (if release_mode is true)'
        type: string
        default: 'v1.0.0'
      release_name:
        description: 'Release name (if release_mode is true)'
        type: string
        default: 'Release v1.0.0'

jobs:
  # Вызываем Linux
  call-build-linux:
    uses: ./.github/workflows/build-linux.yml
    if: inputs.build_linux == 'true'
    with:
      build_mode: ${{ inputs.build_mode }}
    secrets: inherit

  # Вызываем Android
  call-build-android:
    uses: ./.github/workflows/build-android.yml
    if: inputs.build_android == 'true'
    with:
      build_mode: ${{ inputs.build_mode }}
    secrets: inherit

  # Вызываем Windows
  call-build-windows:
    uses: ./.github/workflows/build-windows.yml
    if: inputs.build_windows == 'true'
    with:
      build_mode: ${{ inputs.build_mode }}
    secrets: inherit

  # Вызываем релиз
  call-publish-release:
    uses: ./.github/workflows/publish-release.yml
    needs: [call-build-linux, call-build-android, call-build-windows]
    if: inputs.release_mode == 'true'
    with:
      release_tag: ${{ inputs.release_tag }}
      release_name: ${{ inputs.release_name }}
    secrets: inherit
